server: 
  port: 8301
  
spring: 
  application: 
    name: sleuth-gateway
  zipkin: 
    base-url: http://192.168.67.59:9411
  sleuth: 
    sampler: 
      percentage: 0.1f  #数据采集百分比 默认0.1f(10笔采集1笔)
    
eureka: 
  client: 
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url: 
      defaultZone: http://192.168.67.59:8201/eureka
    healthCheck: 
      enable: true
  instance: 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90  #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    lease-renewal-interval-in-seconds: 30  #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。