server: 
  port: 8204

spring:
  application: 
    name: server2
  zipkin: 
    base-url: http://192.168.67.44:9411
    
eureka: 
  client:
    service-url: 
      defaultZone: http://192.168.67.44:8201/eureka
    healthCheck: 
      enable: true
  instance: 
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30 # 续约到期时间（默认90秒）