server: 
  port: 9411
spring: 
  application: 
    name: sleuth-zipkin
eureka: 
  client: 
    healthcheck:
      enable: true #开启健康检查
    service-url:
      defaultZone: http://192.168.67.59:8201/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30 # 续约到期时间（默认90秒）